version: '3'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobpostingdb
    ports:
      - '5432:5432'
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d
